platform :ios, '8.0'

target 'CompressingAndUploadingLogFileManager_Example' do
  pod 'CompressingAndUploadingLogFileManager', :path => '../'

  target 'CompressingAndUploadingLogFileManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
